<?php

/**
 * @file
 * Contains quicklink.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_preprocess_html().
 */
function quicklink_preprocess_html(&$variables, $hook) {

  // Load current configuration.
  $config = \Drupal::config('quicklink.quicklinkconfig');

  // Check if local copy of the library exists. If it does not, use the CDN version.
  if (file_exists(drupal_get_path('module', 'quicklink') . '/js/quicklink.umd.js')) {
    $quicklink_library = 'quicklink/quicklink_local';
  }
  else {
    $quicklink_library = 'quicklink/quicklink_cdn';
  }

  $url_patterns_to_exclude =  ['user/logout']; // Automatically exclude the logout link.
  $allowed_domains =  [];

  // Populate and remove line returns from URL patterns to exclude.
  foreach (explode(PHP_EOL, $config->get('url_patterns_to_exclude')) as $value) {
    $url_patterns_to_exclude[] = str_replace("\r", '', $value);
  }

  // Populate and remove line returns from allowed domains.
  foreach (explode(PHP_EOL, $config->get('allowed_domains')) as $value) {
    $allowed_domains[] = str_replace("\r", '', $value);
  }

  // If user is anonymous OR  if "Prefetch for anonymous users only" is NOT selected, load library, load library.
  if (!$variables["logged_in"] || $config->get('prefetch_for_anonymous_users_onl') == 0) {
    $variables['#attached']['library'][] = $quicklink_library;
    $variables['#attached']['library'][] = 'quicklink/quicklink_init';
    $variables['#attached']['drupalSettings']['quicklink']['selector'] = $config->get('selector');
    $variables['#attached']['drupalSettings']['quicklink']['allowed_domains'] = $allowed_domains;
    $variables['#attached']['drupalSettings']['quicklink']['url_patterns_to_exclude'] = $url_patterns_to_exclude;
  }
}
