<?php

/**
 * @file
 * Contains quicklink.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_preprocess_html().
 */
function quicklink_preprocess_html(&$variables, $hook) {

  // Load current configuration.
  $config = \Drupal::config('quicklink.settings');
  $selector = $config->get('selector');

  // Get debug variable.
  $debug = $config->get('enable_debug_mode');
  $debug_log = [];

  // Load the library unless we disable later.
  $load_library = TRUE;

  if (file_exists(DRUPAL_ROOT . '/libraries/quicklink/dist/quicklink.umd.js')) {
    $quicklink_library = 'quicklink/quicklink_local';
    $debug_log[] = 'Local copy of quicklink library detected.';
  }
  else {
    $quicklink_library = 'quicklink/quicklink_cdn';
    $debug_log[] = 'Local copy of quicklink library NOT detected. Will use CDN copy.';
  }

  // Always ignore the logout link.
  $url_patterns_to_ignore = ['user/logout'];
  $debug_log[] = 'Quicklink will ignore "user/logout" URL pattern.';

  $allowed_domains = [];

  // Populate and remove line returns from URL patterns to ignore.
  foreach (explode(PHP_EOL, $config->get('url_patterns_to_ignore')) as $value) {
    $pattern = str_replace("\r", '', $value);

    if (!empty($pattern)) {
      $url_patterns_to_ignore[] = $pattern;
    }
  }

  // Populate and remove line returns from allowed domains.
  foreach (explode(PHP_EOL, $config->get('allowed_domains')) as $value) {
    $domain = str_replace("\r", '', $value);

    if (!empty($domain)) {
      $allowed_domains[] = $domain;
    }
  }

  // Check for "Ignore Hashes" option.
  if ($config->get('ignore_hashes') == 1) {
    $url_patterns_to_ignore[] = '#';
    $debug_log[] = 'Quicklink will ignore URLs with hashes(#).';
  }

  // If "Ignore admin paths" is selected, ignore the admin paths.
  if ($config->get('ignore_admin_paths') == 1) {
    $url_patterns_to_ignore[] = '/admin';
    $url_patterns_to_ignore[] = '/edit';
    $debug_log[] = 'Quicklink will ignore admin URL patterns.';
  }

  // Check for "Content Types" option.
  $node = \Drupal::request()->attributes->get('node');

  if (!empty($node)) {
    $node_type = $node->bundle();
    $config = \Drupal::config('quicklink.settings');
    $ignored_content_types = !empty($config->get('ignored_content_types')) ? $config->get('ignored_content_types') : FALSE;

    if (is_array($ignored_content_types)) {
      if (in_array($node_type, $ignored_content_types)) {
        $load_library = FALSE;
        $debug_log[] = 'Library not loaded because content type ' . $node_type . ' is ignored.';
      }
    }
  }

  // If user is logged in AND "Prefetch for anonymous users only" is selected,
  // do not load library.
  if ($variables['logged_in'] && $config->get('prefetch_for_anonymous_users_onl') == 1) {
    $load_library = FALSE;
    $debug_log[] = 'Library not loaded because user is authenticated.';
  }

  $variables['#attached']['library'][] = 'quicklink/quicklink_init';
  $variables['#attached']['drupalSettings']['quicklink']['ignore_admin_paths'] = $config->get('ignore_admin_paths');
  $variables['#attached']['drupalSettings']['quicklink']['ignore_ajax_links'] = $config->get('ignore_ajax_links');
  $variables['#attached']['drupalSettings']['quicklink']['ignore_file_ext'] = $config->get('ignore_file_ext');
  $variables['#attached']['drupalSettings']['quicklink']['debug'] = $debug;

  if (!empty($selector)) {
    $variables['#attached']['drupalSettings']['quicklink']['selector'] = $selector;
    $debug_log[] = 'Selector for Quicklink to parse: ' . $selector;
  }

  if (!empty($allowed_domains[0])) {
    $variables['#attached']['drupalSettings']['quicklink']['allowed_domains'] = $allowed_domains;
    $debug_log['allowed_domains'][] = $allowed_domains;
  }

  if (!empty($url_patterns_to_ignore[0])) {
    $variables['#attached']['drupalSettings']['quicklink']['url_patterns_to_ignore'] = $url_patterns_to_ignore;
    $debug_log['url_patterns_to_ignore'][] = $url_patterns_to_ignore;
  }

  if ($load_library) {
    if ($config->get('load_polyfill') == 1) {
      $variables['#attached']['library'][] = 'quicklink/quicklink_polyfill';
      $debug_log[] = 'Intersection Observer polyfill library loaded';
    }

    $variables['#attached']['library'][] = $quicklink_library;
  }

  if ($debug) {
    $variables['#attached']['drupalSettings']['quicklink']['debug'] = 1;
    $variables['#attached']['library'][] = 'quicklink/quicklink_debug';
    $variables['#attached']['drupalSettings']['quicklink']['debug_log'] = $debug_log;
  }
}
